apiVersion: v1
kind: Service
metadata:
  name: go-webapp
  labels:
    app: go-webapp
spec:
  selector:
    app: go-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
